SELECT SUM(NETWEIGHT)
FROM (
    SELECT *, T1.PW*T1.QTI AS NETWEIGHT
    FROM(
        SELECT `PRODUCT`.`PRODUCT_ID`,`PRODUCT`.`PRODUCT_NAME`,`PRODUCT_WEIGHT` AS PW,`HANDLING_INSTRUCTIONS`, SUM(`QUANTITY`) AS QTI
        FROM `SHIPMENT_ITEM`
        INNER JOIN  `SHIPMENT` ON `SHIPMENT_ITEM`.`SHIPMENT_ID` = `SHIPMENT`.`SHIPMENT_ID`
        INNER JOIN  `VF_SHIPMENT_ITEM` ON `SHIPMENT_ITEM`.`SHIPMENT_ID` = `VF_SHIPMENT_ITEM`.`SHIPMENT_ID` AND `SHIPMENT_ITEM`.`SHIPMENT_ITEM_SEQ_ID` = `VF_SHIPMENT_ITEM`.`SHIPMENT_ITEM_SEQ_ID`
        INNER JOIN  `PRODUCT` ON `SHIPMENT_ITEM`.`PRODUCT_ID` = `PRODUCT`.`PRODUCT_ID`
        WHERE `ESTIMATED_SHIP_DATE` >= '2020/00/01' AND `HANDLING_INSTRUCTIONS`= 'STANDARD' AND ORDER_ID IS NULL
        GROUP BY `PRODUCT_ID`
        ) T1
    ) T2